# Generated by Django 3.2.12 on 2022-05-17 17:38

from django.db import migrations, models
import django.db.models.deletion
import mascotas_api.apps.mascota.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('edad_aproximada', models.IntegerField(blank=True, null=True)),
                ('fecha_rescate', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=mascotas_api.apps.mascota.models.upload_location)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.persona')),
                ('vacuna', models.ManyToManyField(blank=True, null=True, to='mascota.Vacuna')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
